spring.application.name=si-moto-backend-exp

#port number
server.port=8080

#db connection
spring.datasource.url = jdbc:postgresql://localhost:5432/si_moto_db
spring.datasource.username=postgres
spring.datasource.password=post@#$6550

#db config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect